[[block]]
block = "battery"
driver = "upower"
format = "$percentage $time $power"
device = "DisplayDevice"

[[block]]
block = "backlight"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "memory"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $timestamp.datetime(f:'%A %Y-%m-%d %R', l:en_US) "
short = " $timestamp.datetime(f:%R) "


